### ISSUE TITLE
  12-setting-up-docker-daemon.md 

### ISSUE THREAD

**Issue by endriv** [ammar-khan/raspberry-pi-3-model-b-plus#1]
Please check if in the line 13 of 12-setting-up-docker-daemon.md you need nano instead of cat. And explain the IP addresses to add.

**Comment by ammar-khan** [comment]
For me `cat` work as it creates a file and insert contents into it at the same time.

If `cat` does not work you can do it using `nano`:

`$ sudo nano /etc/systemd/system/docker.service.d/options.conf`
and then paste following lines into the file:
```
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -H fd:// --bip 172.20.0.1/24 --dns [YOUR-DNS-IP] --dns ::1 --ipv6 --fixed-cidr-v6="[YOUR-RASPBERRY-PI-IP]::/64"
```

then `Ctrl+X` -> `Y` -> `Enter`

I also have explained what IP address you need to add in configuration (make sure you have spaces before and after DNS IP address).
